from pathlib import PurePosixPath
from urllib.parse import unquote, urlparse

from .simple_index import parse_links, version_key
from .source_adapter import run_source_adapter, utc_now


def render_legacy_linux(document):
    lines = [
        "<!-- Generated by windows_rocm_matrix.collect. Do not edit manually. -->",
        "",
        "# Legacy Linux ROCm artifacts",
        "",
        "This adapter records historical Linux release indexes and artifact URLs. It does not infer PyTorch or GPU compatibility from an artifact listing.",
        "",
        "| ROCm release | Artifacts | Source |",
        "| --- | ---: | --- |",
    ]
    for release in document.get("artifact_releases", []):
        lines.append(f"| `{release['release_id']}` | {len(release['artifacts'])} | `{release['source_id']}` |")
    return "\n".join(lines).rstrip() + "\n"


def collect_linux_artifact_releases(source, fetch_text):
    root_html = fetch_text(source["url"])
    releases = []
    for url, _ in parse_links(root_html, source["url"]):
        name = PurePosixPath(urlparse(url).path.rstrip("/")).name
        if not name.startswith("rocm-rel-"):
            continue
        artifacts = []
        page_html = fetch_text(url)
        for artifact_url, _ in parse_links(page_html, url):
            filename = unquote(PurePosixPath(urlparse(artifact_url).path).name)
            if filename.lower().endswith((".whl", ".deb", ".rpm", ".tar.gz", ".run")):
                artifacts.append({"filename": filename, "url": artifact_url})
        releases.append({"release_id": name.removeprefix("rocm-rel-"), "url": url, "artifacts": artifacts, "source_id": source["id"]})
    return sorted(releases, key=lambda item: version_key(item["release_id"]))


def collect_legacy_linux_sources(sources, fetch_text, existing=None, observed_at=None):
    observed_at = observed_at or utc_now()
    existing = existing or {"schema_version": 1, "generated_at": observed_at, "distribution_family": "legacy", "platform": "linux", "sources": {}, "artifact_releases": []}
    records = dict(existing.get("sources", {}))
    releases = list(existing.get("artifact_releases", []))
    results = []
    for source in sources:
        value, result = run_source_adapter(source, lambda source=source: collect_linux_artifact_releases(source, fetch_text), observed_at)
        results.append(result)
        if value is None:
            continue
        releases = [item for item in releases if item["source_id"] != source["id"]]
        releases.extend(value)
        records[source["id"]] = {**source, "observed_at": observed_at}
    return {
        "schema_version": 1,
        "generated_at": observed_at if any(result["status"] == "passed" for result in results) else existing["generated_at"],
        "distribution_family": "legacy",
        "platform": "linux",
        "sources": {key: records[key] for key in sorted(records)},
        "artifact_releases": sorted(releases, key=lambda item: version_key(item["release_id"])),
    }, results
