import re
from pathlib import PurePosixPath
from urllib.parse import unquote, urlparse

from .history import initial_evidence_status
from .simple_index import parse_links, version_key
from .source_adapter import monotonic_generated_at, run_source_adapter, utc_now
from .simple_index import normalize_package_name


def render_legacy_linux(document):
    lines = [
        "<!-- Generated by windows_rocm_matrix.collect. Do not edit manually. -->",
        "",
        "# Legacy Linux ROCm evidence",
        "",
        "This adapter records historical Linux release indexes and artifact URLs. It does not infer PyTorch or GPU compatibility from an artifact listing.",
        "",
        "## Coverage summary",
        "",
        "| ROCm release | Artifacts | Platform support evidence | Runtime verification |",
        "| --- | ---: | --- | --- |",
    ]
    for release in sorted(document.get("artifact_releases", []), key=lambda item: version_key(item["release_id"]), reverse=True):
        lines.append(f"| `{release['release_id']}` | {len(release['artifacts'])} | not collected | not collected |")
    lines.extend([
        "",
        "`observed` artifacts confirm that files were listed at the source. Linux platform, GFX, resolver, runtime, and hardware compatibility evidence is not collected by this adapter.",
        "",
        "## Artifact inventory",
        "",
        "| ROCm release | Artifacts | Source |",
        "| --- | ---: | --- |",
    ])
    for release in sorted(document.get("artifact_releases", []), key=lambda item: version_key(item["release_id"]), reverse=True):
        lines.append(f"| `{release['release_id']}` | {len(release['artifacts'])} | `{release['source_id']}` |")
    return "\n".join(lines).rstrip() + "\n"


def collect_linux_artifact_releases(source, fetch_text):
    root_html = fetch_text(source["url"])
    releases = []
    for url, _ in parse_links(root_html, source["url"]):
        name = PurePosixPath(urlparse(url).path.rstrip("/")).name
        if not name.startswith("rocm-rel-"):
            continue
        artifacts = []
        page_html = fetch_text(url)
        for artifact_url, _ in parse_links(page_html, url):
            filename = unquote(PurePosixPath(urlparse(artifact_url).path).name)
            if filename.lower().endswith((".whl", ".deb", ".rpm", ".tar.gz", ".run")):
                artifacts.append({"filename": filename, "url": artifact_url})
        releases.append({"release_id": name.removeprefix("rocm-rel-"), "url": url, "artifacts": artifacts, "source_id": source["id"]})
    return sorted(releases, key=lambda item: version_key(item["release_id"]))


def collect_legacy_linux_sources(sources, fetch_text, existing=None, observed_at=None):
    observed_at = observed_at or utc_now()
    existing = existing or {"schema_version": 1, "generated_at": observed_at, "distribution_family": "legacy", "platform": "linux", "sources": {}, "artifact_releases": []}
    records = dict(existing.get("sources", {}))
    releases = list(existing.get("artifact_releases", []))
    results = []
    for source in sources:
        value, result = run_source_adapter(source, lambda source=source: collect_linux_artifact_releases(source, fetch_text), observed_at)
        results.append(result)
        if value is None:
            continue
        releases = [item for item in releases if item["source_id"] != source["id"]]
        releases.extend(value)
        records[source["id"]] = {**source, "observed_at": observed_at}
    return {
        "schema_version": 1,
        "generated_at": monotonic_generated_at(existing, observed_at) if any(result["status"] == "passed" for result in results) else existing["generated_at"],
        "distribution_family": "legacy",
        "platform": "linux",
        "sources": {key: records[key] for key in sorted(records)},
        "artifact_releases": sorted(releases, key=lambda item: version_key(item["release_id"])),
    }, results


def version_series(version):
    match = re.match(r"(\d+\.\d+)", version or "")
    return match.group(1) if match else None


def framework_match(torch_version, torchvision_version, torchaudio_version, framework_compatibility):
    torch_series = version_series(torch_version)
    torchvision_series = version_series(torchvision_version)
    torchaudio_series = version_series(torchaudio_version)
    return any(
        rule.get("torch_series") == torch_series
        and rule.get("torchvision_series") == torchvision_series
        and rule.get("torchaudio_series") == torchaudio_series
        for rule in framework_compatibility
    )


def classify_legacy_linux_framework(history, framework_compatibility):
    for candidate in history.get("candidates", []):
        if candidate.get("distribution_family") != "legacy" or candidate.get("platform") != "linux":
            continue
        if not framework_compatibility:
            candidate["framework_compatibility"] = "not_collected"
        else:
            candidate["framework_compatibility"] = "verified" if framework_match(
                candidate.get("torch_version"), candidate.get("torchvision_version"), candidate.get("torchaudio_version"), framework_compatibility
            ) else "incompatible"
    return history


def build_legacy_linux_candidates(document, framework_compatibility=()):
    candidates = []
    for release in document.get("artifact_releases", []):
        packages = {"torch": [], "torchvision": [], "torchaudio": []}
        for item in release.get("artifacts", []):
            filename = item["filename"]
            if not filename.endswith(".whl"):
                continue
            parts = filename[:-4].split("-")
            if len(parts) < 5:
                continue
            package = normalize_package_name(parts[0])
            if package not in packages:
                continue
            packages[package].append({
                "package": package,
                "version": parts[1],
                "python_tag": parts[-3],
                "abi_tag": parts[-2],
                "platform_tag": parts[-1],
                "filename": filename,
                "url": item["url"],
            })
        if not all(packages.values()):
            continue
        for torch in packages["torch"]:
            vision_options = [item for item in packages["torchvision"] if item["python_tag"] == torch["python_tag"]]
            audio_options = [item for item in packages["torchaudio"] if item["python_tag"] == torch["python_tag"]]
            compatible = [
                (vision, audio)
                for vision in vision_options
                for audio in audio_options
                if framework_match(torch["version"], vision["version"], audio["version"], framework_compatibility)
            ]
            if not compatible:
                continue
            vision, audio = max(compatible, key=lambda pair: (version_key(pair[0]["version"]), version_key(pair[1]["version"])))
            candidate_id = ":".join(("legacy", "linux", "stable", release["release_id"], torch["version"], vision["version"], audio["version"], torch["python_tag"]))
            candidates.append({
                "id": candidate_id,
                "distribution_family": "legacy",
                "platform": "linux",
                "channel": "stable",
                "rocm_version": release["release_id"],
                "hip_version": None,
                "framework_compatibility": "verified",
                "evidence_status": initial_evidence_status(),
                "resolver_results": [],
                "torch_version": torch["version"],
                "torchvision_version": vision["version"],
                "torchaudio_version": audio["version"],
                "python_tags": [torch["python_tag"]],
                "gfx_support": "unknown",
                "gfx_targets": [],
                "source_id": "legacy-linux-artifacts",
                "wheel_urls": [torch["url"], vision["url"], audio["url"]],
            })
    return candidates
