from pathlib import Path

from .persistence import atomic_write_text


def status_mark(value):
    return "Yes" if value else "No"


def render_compatibility_matrix(matrix):
    lines = [
        "<!-- Generated by windows_rocm_matrix.collect. Do not edit manually. -->",
        "",
        "# ROCm compatibility matrix",
        "",
        "This matrix keeps official release documentation, TheRock development status, and package availability as separate evidence. A package being available does not prove runtime or hardware compatibility.",
        "",
        f"Generated at: `{matrix['generated_at']}`",
        "",
        "## Released Windows support",
        "",
        "Product names come from AMD GPU specifications. A product sharing a GFX target is not automatically documented as supported unless it is represented by the compatibility matrix selector IDs.",
        "",
        "| GFX target | ROCm | Windows | Selector IDs | Products in GPU specifications |",
        "| --- | --- | --- | --- | --- |",
    ]
    for target in matrix["targets"]:
        support = target_platform(target, "windows").get("release_support")
        if support is None:
            continue
        products = ", ".join(target["products"]) or "—"
        selectors = ", ".join(f"`{item}`" for item in support["selector_ids"]) or "—"
        windows = ", ".join(support["windows_versions"]) or "—"
        lines.append(f"| `{target['gfx']}` | {support['rocm_version']} | {windows} | {selectors} | {products} |")

    lines.extend(
        [
            "",
            "## TheRock Windows development status",
            "",
            "Build Passing only means an artifact was produced. Sanity Tested and Release Ready are reported independently by TheRock.",
            "",
            "| GFX target | Architecture | Build passing | Sanity tested | Release ready |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for target in matrix["targets"]:
        status = target_platform(target, "windows").get("therock_status")
        if status is None:
            continue
        lines.append(
            f"| `{target['gfx']}` | {status['architecture']} | {status_mark(status['build_passing'])} | "
            f"{status_mark(status['sanity_tested'])} | {status_mark(status['release_ready'])} |"
        )

    lines.extend(
        [
            "",
            "## Device package availability",
            "",
            "Versions are selected independently per device package and do not establish a resolver-compatible set.",
            "",
            "| Platform | GFX target | Channel | ROCm device | Torch device | TorchVision device | All available |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    channel_order = {"stable": 0, "nightly": 1, "staging": 2}
    platform_order = {"windows": 0, "linux": 1, "macos": 2, "unknown": 3}
    for target in matrix["targets"]:
        for platform, platform_data in sorted(
            target.get("platforms", {}).items(),
            key=lambda item: platform_order.get(item[0], 99),
        ):
            channels = platform_data.get("package_channels", {})
            for channel, packages in sorted(channels.items(), key=lambda item: channel_order.get(item[0], 99)):
                values = [
                    packages["rocm_device_version"] or "—",
                    packages["torch_device_version"] or "—",
                    packages["torchvision_device_version"] or "—",
                ]
                lines.append(
                    f"| {platform} | `{target['gfx']}` | {channel} | {' | '.join(values)} | "
                    f"{status_mark(packages['all_device_packages_available'])} |"
                )
    return "\n".join(lines).rstrip() + "\n"


def target_platform(target, platform):
    return target.get("platforms", {}).get(
        platform,
        {
            "release_support": target.get("windows_release_support"),
            "therock_status": target.get("therock_windows_status"),
        },
    )


def write_compatibility_document(matrix, output_path):
    path = Path(output_path)
    atomic_write_text(path, render_compatibility_matrix(matrix))
