import json
from pathlib import Path

from .simple_index import gfx_key, latest_version, package_names_for_target


def render_snapshots(snapshot_paths):
    snapshots = []
    for path in sorted(snapshot_paths):
        with Path(path).open(encoding="utf-8") as handle:
            snapshots.append(json.load(handle))

    lines = [
        "<!-- Generated by windows_rocm_matrix.collect. Do not edit manually. -->",
        "",
        "# ROCm package availability",
        "",
        "A package listed here was observed in an official AMD index. Versions are selected independently per package; availability does not prove a compatible set, dependency resolution, or runtime compatibility. Use the historical candidate catalog for coherent package sets.",
        "",
    ]

    channel_order = {"stable": 0, "nightly": 1, "staging": 2}
    platform_order = {"windows": 0, "linux": 1, "macos": 2, "unknown": 3}
    for snapshot in sorted(
        snapshots,
        key=lambda item: (
            platform_order.get(item["source"].get("platform", "windows"), 99),
            channel_order.get(item["source"]["channel"], 99),
        ),
    ):
        source = snapshot["source"]
        platform = source.get("platform", "windows")
        lines.extend(
            [
                f"## {platform.title()} — {source['channel'].title()}",
                "",
                f"- Source: {source['url']}",
                f"- Last observed: `{snapshot['last_observed_at']}`",
                "",
                "| GFX target | ROCm device | Torch device | TorchVision device | All device packages available |",
                "| --- | --- | --- | --- | --- |",
            ]
        )
        packages = snapshot["packages"]
        for target in sorted(snapshot["gfx_targets"], key=lambda item: gfx_key(item["gfx"]), reverse=True):
            names = package_names_for_target(target["gfx"])
            versions = [latest_version(packages.get(name, [])) for name in names]
            cells = [version or "—" for version in versions]
            available = "Yes" if target["all_device_packages_available"] else "No"
            lines.append(f"| `{target['gfx']}` | {' | '.join(cells)} | {available} |")
        if not snapshot["gfx_targets"]:
            lines.append("| — | — | — | — | No targets discovered |")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_rendered_document(snapshot_paths, output_path):
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_snapshots(snapshot_paths), encoding="utf-8", newline="\n")
