import json
from pathlib import Path

from .simple_index import latest_version, package_names_for_target


def render_snapshots(snapshot_paths):
    snapshots = []
    for path in sorted(snapshot_paths):
        with Path(path).open(encoding="utf-8") as handle:
            snapshots.append(json.load(handle))

    lines = [
        "<!-- Generated by windows_rocm_matrix.collect. Do not edit manually. -->",
        "",
        "# ROCm package availability",
        "",
        "A package listed here was observed in an official AMD index. Versions are selected independently per package; availability does not prove a compatible set, dependency resolution, or runtime compatibility.",
        "",
    ]

    channel_order = {"stable": 0, "nightly": 1, "staging": 2}
    for snapshot in sorted(snapshots, key=lambda item: channel_order[item["source"]["channel"]]):
        source = snapshot["source"]
        lines.extend(
            [
                f"## {source['channel'].title()}",
                "",
                f"- Source: {source['url']}",
                f"- Last observed: `{snapshot['last_observed_at']}`",
                "",
                "| GFX target | ROCm device | Torch device | TorchVision device | All device packages available |",
                "| --- | --- | --- | --- | --- |",
            ]
        )
        packages = snapshot["packages"]
        for target in snapshot["gfx_targets"]:
            names = package_names_for_target(target["gfx"])
            versions = [latest_version(packages.get(name, [])) for name in names]
            cells = [version or "—" for version in versions]
            available = "Yes" if target["all_device_packages_available"] else "No"
            lines.append(f"| `{target['gfx']}` | {' | '.join(cells)} | {available} |")
        if not snapshot["gfx_targets"]:
            lines.append("| — | — | — | — | No targets discovered |")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_rendered_document(snapshot_paths, output_path):
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_snapshots(snapshot_paths), encoding="utf-8", newline="\n")
